### ISSUE TITLE
1.18 Premium Account Can't Connect To Youre Services

### ISSUE THREAD

**Issue by Commandthealien** [EyezahMC/Cosmetica#33] opened 2022-04-30 03:13 UTC
I Get The Can't Authenticate Account And I Have Great Internet And Have A Premiumn Account And AM Using 1.18 Version Of Cosmetica

**Comment by valoeghese** [comment] 2022-04-30 21:06
Duplicate of #29, known issue that happens occasionally

**Comment by eyezahhhh** [comment] 2022-05-03 03:15
Fixed in version [1.1.1](https://cosmetica.cc/join).

**Closed by eyezahhhh** 2022-05-03 03:15 UTC
Labels: bug, duplicate
